In [1]:
import pymongo
import pandas as pd

Connect to MongoDB

In [2]:
CWL = 'xchen165'
SNUM = '97572945'

connection_string = f"mongodb://{CWL}:a{SNUM}@localhost:27017/{CWL}"
client = pymongo.MongoClient(connection_string)

# Access your database and movies collection
db = client[CWL]
collection = db["movies"]

RQ1_1

In [3]:
pipeline1_1 = [
    {
        '$match': {
            'year': {
                '$gte': 2015, 
                '$lte': 2020
            }, 
            'isAdult': {
                '$ne': None
            }, 
            'ratings.imdb': {
                '$ne': None
            }, 
            'ratings.rottenTomatoes': {
                '$ne': None
            }, 
            'akas_regions': {
                '$in': [
                    'US', 'CA'
                ]
            }
        }
    }, {
        '$group': {
            '_id': '$isAdult', 
            'avg_imdb': {
                '$avg': '$ratings.imdb'
            }, 
            'min_imdb': {
                '$min': '$ratings.imdb'
            }, 
            'max_imdb': {
                '$max': '$ratings.imdb'
            }, 
            'std_imdb': {
                '$stdDevPop': '$ratings.imdb'
            }, 
            'avg_rt': {
                '$avg': '$ratings.rottenTomatoes'
            }, 
            'min_rt': {
                '$min': '$ratings.rottenTomatoes'
            }, 
            'max_rt': {
                '$max': '$ratings.rottenTomatoes'
            }, 
            'std_rt': {
                '$stdDevPop': '$ratings.rottenTomatoes'
            }, 
            'count': {
                '$sum': 1
            }
        }
    }, {
        '$project': {
            '_id': 0, 
            'isAdult': '$_id', 
            'count': 1, 
            'avg_imdb': 1, 
            'min_imdb': 1, 
            'max_imdb': 1, 
            'std_imdb': 1, 
            'avg_rt': 1, 
            'min_rt': 1, 
            'max_rt': 1, 
            'std_rt': 1
        }
    }
]

In [4]:
result1_1 = list(collection.aggregate(pipeline1_1))
df1_1 = pd.DataFrame(result1_1)

df1_1

,avg_imdb,min_imdb,max_imdb,std_imdb,avg_rt,min_rt,max_rt,std_rt,count,isAdult
0,61.622667,13.0,88.0,11.476597,59.556000,12.0,97.0,13.210862,750,False
1,59.308511,13.0,85.0,11.152101,61.739953,34.0,98.0,11.460735,846,True

RQ1_2

In [5]:
pipeline1_2 = [
    {
        '$match': {
            'year': {
                '$gte': 2015, 
                '$lte': 2020
            }, 
            'isAdult': {
                '$ne': None
            }, 
            'ratings.imdb': {
                '$ne': None
            }, 
            'ratings.rottenTomatoes': {
                '$ne': None
            }, 
            'akas_regions': {
                '$in': [
                    'US', 'CA'
                ]
            }
        }
    }, {
        '$facet': {
            'adult_imdb': [
                {
                    '$match': {
                        'isAdult': True, 
                        'ratings.imdb': {
                            '$ne': None
                        }
                    }
                }, {
                    '$group': {
                        '_id': '$ratings.imdb', 
                        'count': {
                            '$sum': 1
                        }
                    }
                }, {
                    '$sort': {
                        '_id': 1
                    }
                }
            ], 
            'adult_rt': [
                {
                    '$match': {
                        'isAdult': True, 
                        'ratings.rottenTomatoes': {
                            '$ne': None
                        }
                    }
                }, {
                    '$group': {
                        '_id': '$ratings.rottenTomatoes', 
                        'count': {
                            '$sum': 1
                        }
                    }
                }, {
                    '$sort': {
                        '_id': 1
                    }
                }
            ], 
            'non_adult_imdb': [
                {
                    '$match': {
                        'isAdult': False, 
                        'ratings.imdb': {
                            '$ne': None
                        }
                    }
                }, {
                    '$group': {
                        '_id': '$ratings.imdb', 
                        'count': {
                            '$sum': 1
                        }
                    }
                }, {
                    '$sort': {
                        '_id': 1
                    }
                }
            ], 
            'non_adult_rt': [
                {
                    '$match': {
                        'isAdult': False, 
                        'ratings.rottenTomatoes': {
                            '$ne': None
                        }
                    }
                }, {
                    '$group': {
                        '_id': '$ratings.rottenTomatoes', 
                        'count': {
                            '$sum': 1
                        }
                    }
                }, {
                    '$sort': {
                        '_id': 1
                    }
                }
            ]
        }
    }, {
        '$project': {
            '_id': 0, 
            'adultIMDb': '$adult_imdb', 
            'adultRT': '$adult_rt', 
            'nonAdultIMDb': '$non_adult_imdb', 
            'nonAdultRT': '$non_adult_rt'
        }
    }
]

In [6]:
result1_2 = list(collection.aggregate(pipeline1_2))[0]
adult_imdb = pd.DataFrame(result1_2["adultIMDb"])
adult_imdb["type"] = "Adult"
adult_imdb["source"] = "IMDb"

adult_rt = pd.DataFrame(result1_2["adultRT"])
adult_rt["type"] = "Adult"
adult_rt["source"] = "RottenTomatoes"

non_imdb = pd.DataFrame(result1_2["nonAdultIMDb"])
non_imdb["type"] = "Non-Adult"
non_imdb["source"] = "IMDb"

non_rt = pd.DataFrame(result1_2["nonAdultRT"])
non_rt["type"] = "Non-Adult"
non_rt["source"] = "RottenTomatoes"

# Combine all
df1_2 = pd.concat([adult_imdb, adult_rt, non_imdb, non_rt])

# Rename columns
df1_2.rename(columns={"_id": "rating"}, inplace=True)

df1_2

    rating  count       type          source
0     13.0      1      Adult            IMDb
1     20.0      1      Adult            IMDb
2     28.0      2      Adult            IMDb
3     29.0      4      Adult            IMDb
4     30.0      4      Adult            IMDb
..     ...    ...        ...             ...
59    90.0      2  Non-Adult  RottenTomatoes
60    92.0      2  Non-Adult  RottenTomatoes
61    93.0      1  Non-Adult  RottenTomatoes
62    94.0      1  Non-Adult  RottenTomatoes
63    97.0      1  Non-Adult  RottenTomatoes

[246 rows x 4 columns]

RQ2

In [7]:
pipeline2 = [
    {
        '$match': {
            'year': {
                '$gte': 2015, 
                '$lte': 2020
            }, 
            'isAdult': {
                '$ne': None
            }, 
            'ratings.imdb': {
                '$ne': None
            }, 
            'ratings.rottenTomatoes': {
                '$ne': None
            }, 
            'akas_regions': {
                '$in': [
                    'US', 'CA'
                ]
            }
        }
    }, {
        '$facet': {
            'adult': [
                {
                    '$match': {
                        'isAdult': True
                    }
                }, {
                    '$unwind': {
                        'path': '$genres'
                    }
                }, {
                    '$group': {
                        '_id': '$genres', 
                        'count': {
                            '$sum': 1
                        }
                    }
                }, {
                    '$sort': {
                        'count': -1
                    }
                }
            ], 
            'non_adult': [
                {
                    '$match': {
                        'isAdult': False
                    }
                }, {
                    '$unwind': {
                        'path': '$genres'
                    }
                }, {
                    '$group': {
                        '_id': '$genres', 
                        'count': {
                            '$sum': 1
                        }
                    }
                }, {
                    '$sort': {
                        'count': -1
                    }
                }
            ]
        }
    }, {
        '$project': {
            '_id': 0, 
            'adultGenresCounts': '$adult', 
            'nonAdultGenresCounts': '$non_adult'
        }
    }
]

In [8]:
result2 = list(collection.aggregate(pipeline2))[0]

adult_df = pd.DataFrame(result2["adultGenresCounts"])
adult_df["type"] = "Adult"

non_adult_df = pd.DataFrame(result2["nonAdultGenresCounts"])
non_adult_df["type"] = "Non-Adult"

df2 = pd.concat([adult_df, non_adult_df])
df2.rename(columns={"_id": "genre"}, inplace=True)
df2.head()

      genre  count   type
0     Drama    484  Adult
1    Comedy    218  Adult
2  Thriller    212  Adult
3     Crime    198  Adult
4    Action    179  Adult

RQ3

In [9]:
pipeline3 = [
    {
        '$match': {
            'year': {
                '$gte': 2015, 
                '$lte': 2020
            }, 
            'isAdult': {
                '$ne': None
            }, 
            'ratings.imdb': {
                '$ne': None
            }, 
            'ratings.rottenTomatoes': {
                '$ne': None
            }, 
            'boxOffice.gross': {
                '$ne': None
            }, 
            'akas_regions': {
                '$in': [
                    'US', 'CA'
                ]
            }
        }
    }, {
        '$project': {
            '_id': 0, 
            'title': 0, 
            'year': 0, 
            'genres': 0, 
            'ratings.rottenTomatoes': 0, 
            'akas_regions': 0
        }
    }
]

In [10]:
result3 = list(collection.aggregate(pipeline3))
df3 = pd.DataFrame(result3)
df3["imdb_ratings"] = df3["ratings"].apply(lambda x: x.get("imdb") if isinstance(x, dict) else None)
df3 = df3.drop(columns=["ratings"])
df3["gross"] = df3["boxOffice"].apply(lambda x: x.get("gross") if isinstance(x, dict) else None)
df3 = df3.drop(columns=["boxOffice"])

df3

     isAdult  imdb_ratings      gross
0      False          63.0   63647656
1      False          72.0  519311965
2       True          72.0   23834809
3       True          71.0   64191523
4       True          57.0  113118226
..       ...           ...        ...
198    False          55.0   22304357
199    False          58.0   10987975
200     True          64.0   74922830
201    False          73.0   28477890
202    False          65.0   16069730

[203 rows x 3 columns]

Close Connection

In [11]:
client.close()